# Generated by Django 4.2.3 on 2023-08-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('discord_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('first_training', models.CharField(choices=[('web_dev', 'Web Dev'), ('linux', 'Linux and git'), ('python', 'Python'), ('3d', '3D modeling '), ('design', 'Design')], default='green', max_length=20)),
                ('second_training', models.CharField(choices=[('web_dev', 'Web Dev'), ('linux', 'Linux and git'), ('python', 'Python'), ('3d', '3D modeling '), ('design', 'Design')], default='green', max_length=20)),
                ('pub_source', models.CharField(choices=[('facebook', 'Facebok'), ('instagram', 'Instagram'), ('linkedin', 'Linked In'), ('discord', 'Discord'), ('others', 'Others')], default='green', max_length=20)),
            ],
        ),
    ]
